### PR TITLE
Jp/annulus

### PR DESCRIPTION
**Pull request by ioannisPApapadopoulos**
Implement lowering from weighted (1,1) to unweighted (1,1)

### CODE REVIEW

**Comment by ioannisPApapadopoulos** [comment]
@dlfivefifty @MikaelSlevinsky I think the transforms have been integrated (with the correct re-normalization). Let me know what you think!

**Comment by MikaelSlevinsky** [comment]
If it transforms ZernikeAnnulus.(on_the_grid) to one unit coefficient in the expected degree and order, then it can't be wrong!

Just curious about these lines (for my own understanding)
```julia
# contribution from non-normalized semiclassical Jacobi
     jw = sum.(SemiclassicalJacobiWeight{T}.(t,b,a,0:∞))
```
I thought that `SemiclassicalJacobi` in Julia were orthonormal because the generated Jacobi matrices are symmetric. Maybe it's a difference in weight normalization?

**Comment by ioannisPApapadopoulos** [comment]
Is that true? The Jacobi matrix for `ChebyshevU` is symmetric, but as implemented they are a factor of π/2 from being orthonormal, right? 

```
julia> quadgk(x->sqrt(1-x^2)*ChebyshevU()[x,2]^2, -1, 1, rtol=1e-10)
(1.5707963268010392, 1.0766815610539625e-10) 
```

p.s. the tests failing is to do with some branch issues, I will get it sorted!

**Comment by MikaelSlevinsky** [comment]
Right, so the weight is `2/pi*sqrt(1-x^2)` (generating a probability measure)?

**Comment by ioannisPApapadopoulos** [comment]
Yes sorry, I guess the ChebyshevU case works if you redefine the weight as 2sqrt(1-x^2)/ π. It might be a weight normalization thing. Either way `SemiclassicalJacobi(t,a,b,c)` is not orthonormal with respect to the weight `x^a (1-x)^b (t-x)^c`.

**Comment by MikaelSlevinsky** [comment]
Thanks!

**Comment by TSGut** [comment]
I believe the normalisation thing you're observing may be a result of us generally wanting to maintain p_0(x)=1 ? Orthonormality and that property together only work if the weight is scaled by a constant factor.

**Comment by dlfivefifty** [comment]
We could redefine `orthogonalityweight` so the  condition `sum(orthogonalityweight(P)*P[:,1]) == 1` is always satisfied.

**Comment by ioannisPApapadopoulos** [comment]
Okay, not quite sure what's gone wrong.. the transform tests were working just fine, but now it's complaining about `Grid` not being overloaded. The same issue seems to be happening for standard `Zernike` in `MultivariateOrthogonalPolynomials.jl`. @dlfivefifty do you have any idea clue? I am really puzzled.

**Comment by dlfivefifty** [comment]
Ah looks like its hitting the new `plan_grid_transform`. 

I might change the interface so one overloads `grid(::Zernike, n)` instead of having to make a `FiniteZernike`...

**Comment by dlfivefifty** [comment]
@ioannisPApapadopoulos All set!

**Pull request merged**
